#!/bin/sh

javac Matrix.java
java -classpath . Matrix

read 2
read 1
read 1
read 1
read 1
read 0
read 0
read 0
read 0

if diff myfile.txt testfile1 >/dev/null ; then
	echo Test 1 PASSES
else 
	echo Test 2 FAILS
fi
