#!/bin/sh

for file in code/*.ida
do
language=$(head -1 $file)
language=$(head -1 $file)|sed 's/\(.*\.\)\r/\1/'
echo $language
mv $file srcFile
php 2src.php &>/dev/null
mkdir source/$language/`basename $file .ida`
mv rmv source/$language/`basename $file .ida`/`basename $file ida`$language
done
